username      :
password      : 
round         :
  - date      : 10.04.2021
    course    : blau
    timeslot_h: 19
    timeslot_m: 52
    partner0  :
      - firstName : Simon
        lastName  : Geigenberger
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
  - date      : 10.04.2021
    course    : rot
    timeslot_h: 19
    timeslot_m: 52
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
executedate   : 10.04.2021
executetime_h : 15
executetime_m : 17
executetime_s : 00
workspace     : Windows
weburl        : https://albatros.gc-sl.de/albport/
developermode : True