username      :
password      :
round         :
  - course    : Any
    start_timeslot_h  : 15
    start_timeslot_m  : 00
    end_timeslot_h    : 17
    end_timeslot_m    : 00
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
  - course    : Any
    start_timeslot_h  : 15
    start_timeslot_m  : 00
    end_timeslot_h    : 17
    end_timeslot_m    : 00
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
date          : 30.04.2021
executedate   : 10.04.2021
executetime_h : 15
executetime_m : 17
executetime_s : 00
workspace     : Windows
weburl        : https://albatros.gc-sl.de/albport/
developermode : True