username      :
password      :
roundMINdelay   : 02-00
roundMAXdelay   : 02-30
round         :
  - course    : Red
    start_timeslot: 11-00
    end_timeslot  : 12-00
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
  - course    : Blue
    start_timeslot: 11-00
    end_timeslot  : 11-00
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
date            : 02.05.2021
executedate     : 10.04.2021
executetime     : 15-17-00
workspace       : Windows
weburl          : https://albatros.gc-sl.de/albport/
developermode   : True