username      :
password      :
round         :
  - date      : 07.04.2021
    course    : blau
    timeslot  : 19.52
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
  - date      : 07.04.2021
    course    : rot
    timeslot  : 19.52
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
executedate   : 05.05.2021
executetime   : 09.00.00
workspace     : Windows
weburl        : https://albatros.gc-sl.de/albport/
developmode   : True