username      :
password      : 
round         :
  - date      : 10.04.2021
    course    : blau
    timeslot_h: 19
    timeslot_m: 52
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
  - date      : 10.04.2021
    course    : rot
    timeslot_h: 19
    timeslot_m: 52
    partner0  :
      - firstName : None
        lastName  : None
    partner1  :
      - firstName : None
        lastName  : None
    partner2:
      - firstName : None
        lastName  : None
    partner3  :
      - firstName : None
        lastName  : None
executedate   : 05.05.2021
executetime_h : 09
executetime_m : 09
executetime_s : 09
workspace     : Windows
weburl        : https://albatros.gc-sl.de/albport/